name=PromptHub Theme
module-group-id=agentnxxt
module-incremental-version=1
tags=
short-description=AgentNXXT PromptHub - AI content portal theme
change-log=
page-url=https://github.com/agentnxxt/prompthub
author=AgentNXXT
licenses=Apache-2.0
liferay-versions=7.4.3+
